export const TRADE_CATEGORIES = [
  'Tiling',
  'Bathroom Fitting',
  'Kitchen Fitting',
  'Plumbing',
  'Heating & Gas',
  'Electrical',
  'EV Chargers',
  'Solar & Renewables',
  'General Building',
  'Extensions',
  'Loft Conversions',
  'Loft Boarding & Storage',
  'Garage Conversions',
  'Basement & Cellar Conversions',
  'Bricklaying',
  'Carpentry & Joinery',
  'Plastering & Rendering',
  'Dry Lining & Partitioning',
  'Painting & Decorating',
  'Roofing',
  'Guttering, Fascias & Soffits',
  'Windows & Doors',
  'Glazing',
  'Garage Doors & Automated Gates',
  'Blinds, Shutters & Awnings',
  'Flooring',
  'Carpet Fitting',
  'Screeding & Floor Preparation',
  'Landscaping & Gardening',
  'Tree Surgery',
  'Fencing & Decking',
  'Driveways & Paving',
  'Groundworks',
  'Concrete & Formwork',
  'Piling & Foundations',
  'Drainage',
  'Septic Tanks & Sewage Treatment',
  'Damp Proofing',
  'Insulation',
  'Cladding',
  'Chimneys & Fireplaces',
  'Air Conditioning & Ventilation',
  'Smart Home, CCTV & Alarms',
  'Locksmith',
  'Handyman',
  'Property Maintenance',
  'Appliance Installation',
  'Shopfitting & Commercial Fit-Out',
  'Scaffolding',
  'Demolition',
  'Asbestos Survey & Removal',
  'Waste Removal',
  'Pressure Washing',
  'Cleaning',
  'Pest Control',
  'Garden Rooms & Outbuildings',
  'Conservatories',
  'Swimming Pools & Hot Tubs',
  'Accessibility Adaptations',
  'Stone Masonry',
  'Metalwork & Welding',
  'Architectural & Planning Services',
  'Structural Engineering',
  'Building Surveying',
] as const;

export type TradeCategory = (typeof TRADE_CATEGORIES)[number];

export const SUB_SKILLS: Record<TradeCategory, string[]> = {
  Tiling: ['Bathrooms', 'Wet rooms', 'Kitchen splashbacks', 'Wall tiling', 'Floor tiling', 'Porcelain', 'Ceramic', 'Natural stone', 'Grouting'],
  'Bathroom Fitting': ['Full bathroom refits', 'Showers', 'Wet rooms', 'Baths', 'Toilets', 'Basins', 'Vanity units', 'Bathroom tiling'],
  'Kitchen Fitting': ['Full kitchen fitting', 'Worktops', 'Cabinets', 'Kitchen sinks', 'Splashbacks', 'Appliance installation', 'Kitchen renovations'],
  Plumbing: ['Leaks', 'Pipes', 'Taps', 'Sinks', 'Toilets', 'Showers', 'Bathrooms', 'Radiators', 'Emergency callout'],
  'Heating & Gas': ['Boilers', 'Boiler servicing', 'Central heating', 'Radiators', 'Gas appliances', 'Underfloor heating', 'Heating repairs'],
  Electrical: ['Domestic electrics', 'Rewires', 'Sockets', 'Lighting', 'Consumer units', 'Testing', 'Fault finding', 'Outdoor electrics'],
  'EV Chargers': ['Home EV chargers', 'Commercial chargers', 'Charger upgrades', 'Load management'],
  'Solar & Renewables': ['Solar panels', 'Battery storage', 'Heat pumps', 'Renewable energy systems'],
  'General Building': ['Renovations', 'Structural alterations', 'Open-plan conversions', 'Property refurbishment', 'Building repairs'],
  Extensions: ['Single-storey extensions', 'Double-storey extensions', 'Rear extensions', 'Side returns', 'Wraparound extensions'],
  'Loft Conversions': ['Dormers', 'Hip-to-gable', 'Velux conversions', 'Loft rooms', 'Loft insulation'],
  'Loft Boarding & Storage': ['Loft boarding', 'Raised boarding', 'Loft ladders', 'Loft shelving', 'Loft hatches'],
  'Garage Conversions': ['Garage rooms', 'Home offices', 'Utility rooms', 'Annexes'],
  'Basement & Cellar Conversions': ['Basement conversions', 'Cellar conversions', 'Tanking', 'Basement rooms', 'Waterproofing'],
  Bricklaying: ['Walls', 'Repointing', 'Brick repairs', 'Blockwork', 'Garden walls', 'Chimneys'],
  'Carpentry & Joinery': ['First fix', 'Second fix', 'Doors', 'Skirting', 'Stairs', 'Cabinetry', 'Built-in storage'],
  'Plastering & Rendering': ['Skimming', 'Plaster repairs', 'Dry lining', 'Rendering', 'Ceilings', 'External render'],
  'Dry Lining & Partitioning': ['Plasterboard', 'Stud walls', 'Partition walls', 'Dot and dab', 'Suspended ceilings', 'Office partitions'],
  'Painting & Decorating': ['Interior painting', 'Exterior painting', 'Wallpapering', 'Woodwork', 'Feature walls', 'Spray painting'],
  Roofing: ['Pitched roofs', 'Flat roofs', 'Roof repairs', 'Leadwork', 'Tiles', 'Slates', 'Roof leaks'],
  'Guttering, Fascias & Soffits': ['Gutters', 'Downpipes', 'Fascias', 'Soffits', 'Rainwater systems'],
  'Windows & Doors': ['Windows', 'Front doors', 'French doors', 'Bi-fold doors', 'UPVC', 'Composite doors'],
  Glazing: ['Double glazing', 'Glass replacement', 'Mirrors', 'Shopfront glass', 'Emergency glazing'],
  'Garage Doors & Automated Gates': ['Garage doors', 'Roller doors', 'Sectional doors', 'Automated gates', 'Gate motors', 'Repairs'],
  'Blinds, Shutters & Awnings': ['Window blinds', 'Plantation shutters', 'Roller blinds', 'Awnings', 'Motorised blinds'],
  Flooring: ['Laminate', 'LVT', 'Vinyl', 'Wood flooring', 'Floor preparation', 'Floor repairs'],
  'Carpet Fitting': ['Carpets', 'Underlay', 'Stairs', 'Carpet tiles', 'Repairs'],
  'Screeding & Floor Preparation': ['Floor screeding', 'Self-levelling compound', 'Latex screed', 'Subfloor preparation', 'DPM installation'],
  'Landscaping & Gardening': ['Garden design', 'Lawns', 'Planting', 'Patios', 'Garden maintenance', 'Artificial grass'],
  'Tree Surgery': ['Tree removal', 'Pruning', 'Stump grinding', 'Hedge reduction', 'Crown reduction'],
  'Fencing & Decking': ['Fences', 'Gates', 'Timber decking', 'Composite decking', 'Fence repairs'],
  'Driveways & Paving': ['Block paving', 'Tarmac', 'Resin driveways', 'Patios', 'Paths', 'Paving repairs'],
  Groundworks: ['Foundations', 'Excavation', 'Concrete', 'Site preparation', 'Trenches', 'Footings'],
  'Concrete & Formwork': ['Concrete slabs', 'Reinforced concrete', 'Formwork', 'Concrete bases', 'Concrete repairs'],
  'Piling & Foundations': ['Mini piling', 'Underpinning', 'Foundation piling', 'Raft foundations', 'Foundation repairs'],
  Drainage: ['Blocked drains', 'Drain repairs', 'CCTV surveys', 'Soakaways', 'Drain replacement'],
  'Septic Tanks & Sewage Treatment': ['Septic tanks', 'Treatment plants', 'Cesspits', 'Drainage fields', 'Emptying and servicing'],
  'Damp Proofing': ['Rising damp', 'Penetrating damp', 'Tanking', 'Mould treatment', 'Basement waterproofing'],
  Insulation: ['Loft insulation', 'Wall insulation', 'Floor insulation', 'Sound insulation', 'Thermal upgrades'],
  Cladding: ['External cladding', 'Timber cladding', 'Composite cladding', 'Repairs'],
  'Chimneys & Fireplaces': ['Chimney repairs', 'Chimney sweeping', 'Fireplace installation', 'Flue work', 'Stoves'],
  'Air Conditioning & Ventilation': ['Air conditioning', 'MVHR', 'Extractor fans', 'Ventilation', 'Servicing'],
  'Smart Home, CCTV & Alarms': ['CCTV', 'Burglar alarms', 'Smart lighting', 'Video doorbells', 'Access control', 'Home automation'],
  Locksmith: ['Lock changes', 'Emergency entry', 'UPVC locks', 'Security upgrades', 'Key cutting'],
  Handyman: ['Small repairs', 'Shelves', 'Flat-pack assembly', 'Curtain poles', 'Picture hanging', 'Odd jobs'],
  'Property Maintenance': ['Reactive repairs', 'Planned maintenance', 'Landlord maintenance', 'Minor building repairs', 'Property inspections'],
  'Appliance Installation': ['Ovens', 'Hobs', 'Dishwashers', 'Washing machines', 'Cooker hoods'],
  'Shopfitting & Commercial Fit-Out': ['Retail fit-outs', 'Office fit-outs', 'Shop counters', 'Partitions', 'Ceilings', 'Commercial refurbishments'],
  Scaffolding: ['Domestic scaffolds', 'Access towers', 'Roof scaffolds', 'Temporary access'],
  Demolition: ['Internal strip-out', 'Outbuilding demolition', 'Wall removal', 'Site clearance'],
  'Asbestos Survey & Removal': ['Asbestos surveys', 'Sampling', 'Asbestos removal', 'Garage roof removal', 'Encapsulation'],
  'Waste Removal': ['Rubbish clearance', 'Builders waste', 'House clearance', 'Garden waste'],
  'Pressure Washing': ['Driveways', 'Patios', 'Decking', 'Walls', 'Exterior cleaning'],
  Cleaning: ['End-of-build cleaning', 'Deep cleaning', 'Carpet cleaning', 'Window cleaning', 'Gutter cleaning'],
  'Pest Control': ['Rodents', 'Wasps', 'Insects', 'Bird control', 'Pest proofing'],
  'Garden Rooms & Outbuildings': ['Garden offices', 'Summerhouses', 'Sheds', 'Studios', 'Outdoor rooms'],
  Conservatories: ['Conservatory installation', 'Roof replacement', 'Repairs', 'Orangeries'],
  'Swimming Pools & Hot Tubs': ['Pool installation', 'Hot tubs', 'Pool maintenance', 'Plant rooms'],
  'Accessibility Adaptations': ['Grab rails', 'Ramps', 'Accessible bathrooms', 'Door widening', 'Mobility adaptations'],
  'Stone Masonry': ['Stone walls', 'Stone repairs', 'Natural stone', 'Repointing', 'Restoration'],
  'Metalwork & Welding': ['Gates', 'Railings', 'Structural steel', 'Welding repairs', 'Balustrades'],
  'Architectural & Planning Services': ['Planning drawings', 'Building regulations drawings', 'Extensions', 'Loft plans', 'Planning applications'],
  'Structural Engineering': ['Structural calculations', 'Steel beam design', 'Load-bearing walls', 'Foundation design', 'Structural surveys'],
  'Building Surveying': ['Building surveys', 'Defect inspections', 'Snagging', 'Party wall', 'Condition reports'],
};

export const PROPERTY_TYPES = ['House', 'Flat', 'Bungalow', 'Commercial', 'Other'] as const;
export const URGENCY_OPTIONS = ['Flexible', 'Within 1 month', 'Within 2 weeks', 'Urgent'] as const;
export const BUDGET_OPTIONS = ['Under £500', '£500–£1,500', '£1,500–£5,000', '£5,000–£15,000', '£15,000+'] as const;
export const RADIUS_OPTIONS = ['5', '10', '15', '25', '50', '75'] as const;
export const TRADER_BIO_MIN_LENGTH = 50;

export const SUBSCRIPTION_TIERS = {
  free: { name: 'Free', price: '£0', features: ['Shareable public profile', 'Gallery and reviews'] },
  basic: { name: 'Basic Direct Leads', price: '£19.99/mo', features: ['Direct contact form', 'Receive customer leads'] },
  featured: { name: 'Featured Search', price: '£29.99/mo', features: ['Featured directory position', 'Unlimited direct quotes', 'Everything in Basic'] },
} as const;
