import { MD3LightTheme } from 'react-native-paper';

export const colors = {
  primary: '#D35400',
  primaryDark: '#9C3E00',
  primarySoft: '#FFF0E5',
  secondary: '#F2A65A',
  secondarySoft: '#FFF6E8',
  accent: '#2F7D74',
  accentSoft: '#E8F4F2',
  blue: '#3F6F8F',
  blueSoft: '#EAF2F7',
  background: '#F5F2ED',
  surface: '#FBFAF8',
  surfaceRaised: '#FFFFFF',
  surfaceSoft: '#F7F3EE',
  surfaceStrong: '#EEE7DF',
  charcoal: '#252A31',
  charcoalSoft: '#3B4148',
  border: '#E1D9D1',
  text: '#24272B',
  muted: '#6E716F',
  success: '#2E7D32',
  danger: '#B42318',
  warning: '#B76610',
  info: '#356C95',
} as const;

export const paperTheme = {
  ...MD3LightTheme,
  roundness: 8,
  colors: {
    ...MD3LightTheme.colors,
    primary: colors.primary,
    onPrimary: '#FFFFFF',
    primaryContainer: colors.primarySoft,
    onPrimaryContainer: colors.primaryDark,
    secondary: colors.secondary,
    secondaryContainer: colors.secondarySoft,
    onSecondaryContainer: colors.charcoal,
    tertiary: colors.accent,
    tertiaryContainer: colors.accentSoft,
    background: colors.background,
    surface: colors.surfaceRaised,
    surfaceVariant: colors.surfaceSoft,
    outline: colors.border,
    outlineVariant: '#ECE5DE',
    onSurface: colors.text,
    onSurfaceVariant: colors.muted,
    error: colors.danger,
  },
};
