import type { Job, TraderProfile } from '@/types';

const now = new Date('2026-09-04T12:00:00.000Z').toISOString();

export const demoTraders: TraderProfile[] = [
  {
    id: 'demo-joe-loveridge-tiling',
    userId: 'demo-user-joe-loveridge',
    businessName: 'Joe Loveridge Tiling',
    tradeCategory: 'Tiling',
    subSkills: ['Bathrooms', 'Wet rooms', 'Floors', 'Natural stone'],
    bio: 'Wall and floor tiler covering bathrooms, wet rooms, floors and full rip-outs. Straight quotes, tidy work and no mystery builder nonsense.',
    radiusMiles: 35,
    postcode: 'TW18',
    locationLabel: 'Staines-upon-Thames',
    externalLinks: {},
    photos: [],
    subscriptionTier: 'featured',
    isSubscriptionActive: true,
    trialEndsAt: '2026-09-18T12:00:00.000Z',
    averageRating: 4.9,
    reviewCount: 37,
  },
  {
    id: 'demo-orange-square-plastering',
    userId: 'demo-user-orange-square',
    businessName: 'Orange Square Plastering',
    tradeCategory: 'Plastering',
    subSkills: ['Skimming', 'Rendering', 'Repair work'],
    bio: 'Domestic plastering team for clean skims, patch repairs, ceilings and small renovation projects across West London and Surrey.',
    radiusMiles: 25,
    locationLabel: 'Hounslow',
    externalLinks: {},
    photos: [],
    subscriptionTier: 'basic',
    isSubscriptionActive: true,
    trialEndsAt: '2026-09-18T12:00:00.000Z',
    averageRating: 4.7,
    reviewCount: 18,
  },
  {
    id: 'demo-thames-valley-sparks',
    userId: 'demo-user-thames-sparks',
    businessName: 'Thames Valley Sparks',
    tradeCategory: 'Electrical',
    subSkills: ['Domestic', 'Testing', 'EV chargers'],
    bio: 'NICEIC-style domestic electrical work, fault finding, consumer unit changes and landlord safety certificates.',
    radiusMiles: 40,
    locationLabel: 'Woking',
    externalLinks: {},
    photos: [],
    subscriptionTier: 'featured',
    isSubscriptionActive: true,
    trialEndsAt: '2026-09-18T12:00:00.000Z',
    averageRating: 4.8,
    reviewCount: 29,
  },
  {
    id: 'demo-copperline-plumbing',
    userId: 'demo-user-copperline',
    businessName: 'Copperline Plumbing',
    tradeCategory: 'Plumbing',
    subSkills: ['Bathrooms', 'Leaks', 'Heating'],
    bio: 'Plumbing repairs, bathroom installs and heating maintenance with clear callout pricing and tidy handover notes.',
    radiusMiles: 30,
    locationLabel: 'Guildford',
    externalLinks: {},
    photos: [],
    subscriptionTier: 'basic',
    isSubscriptionActive: true,
    trialEndsAt: '2026-09-18T12:00:00.000Z',
    averageRating: 4.6,
    reviewCount: 22,
  },
  {
    id: 'demo-oak-and-level-joinery',
    userId: 'demo-user-oak-level',
    businessName: 'Oak & Level Joinery',
    tradeCategory: 'Joinery',
    subSkills: ['Second fix', 'Doors', 'Cabinetry'],
    bio: 'Second fix joinery, internal doors, storage, skirting and made-to-measure cabinetry for homes and small commercial spaces.',
    radiusMiles: 20,
    locationLabel: 'Richmond',
    externalLinks: {},
    photos: [],
    subscriptionTier: 'basic',
    isSubscriptionActive: true,
    trialEndsAt: '2026-09-18T12:00:00.000Z',
    averageRating: 4.9,
    reviewCount: 14,
  },
  {
    id: 'demo-apex-roof-care',
    userId: 'demo-user-apex-roof',
    businessName: 'Apex Roof Care',
    tradeCategory: 'Roofing',
    subSkills: ['Pitched', 'Flat', 'Repairs', 'Guttering'],
    bio: 'Roof repairs, flat roof renewals, guttering and storm damage callouts with photo reports before and after the job.',
    radiusMiles: 45,
    locationLabel: 'Epsom',
    externalLinks: {},
    photos: [],
    subscriptionTier: 'featured',
    isSubscriptionActive: true,
    trialEndsAt: '2026-09-18T12:00:00.000Z',
    averageRating: 4.5,
    reviewCount: 31,
  },
  {
    id: 'demo-brickline-builders',
    userId: 'demo-user-brickline',
    businessName: 'Brickline Builders',
    tradeCategory: 'General Building',
    subSkills: ['Extensions', 'Renovations', 'Brickwork'],
    bio: 'Small building works, knock-throughs, brick repairs and renovation support for homeowners who want straight answers.',
    radiusMiles: 35,
    locationLabel: 'Slough',
    externalLinks: {},
    photos: [],
    subscriptionTier: 'basic',
    isSubscriptionActive: true,
    trialEndsAt: '2026-09-18T12:00:00.000Z',
    averageRating: 4.4,
    reviewCount: 11,
  },
  {
    id: 'demo-clean-cut-tiling',
    userId: 'demo-user-clean-cut',
    businessName: 'Clean Cut Tiling Co',
    tradeCategory: 'Tiling',
    subSkills: ['Floors', 'Exterior', 'Bathrooms'],
    bio: 'Floor tiling, patios, splashbacks and bathroom refreshes with fixed written quotes and careful preparation.',
    radiusMiles: 25,
    locationLabel: 'Reading',
    externalLinks: {},
    photos: [],
    subscriptionTier: 'basic',
    isSubscriptionActive: true,
    trialEndsAt: '2026-09-18T12:00:00.000Z',
    averageRating: 4.6,
    reviewCount: 16,
  },
  {
    id: 'demo-brightwire-electrical',
    userId: 'demo-user-brightwire',
    businessName: 'Brightwire Electrical',
    tradeCategory: 'Electrical',
    subSkills: ['Rewires', 'Domestic', 'Commercial'],
    bio: 'Rewires, kitchen circuits, lighting upgrades and shop maintenance work across London and the M25 corridor.',
    radiusMiles: 50,
    locationLabel: 'Uxbridge',
    externalLinks: {},
    photos: [],
    subscriptionTier: 'basic',
    isSubscriptionActive: true,
    trialEndsAt: '2026-09-18T12:00:00.000Z',
    averageRating: 4.3,
    reviewCount: 9,
  },
  {
    id: 'demo-flowfix-plumbing',
    userId: 'demo-user-flowfix',
    businessName: 'FlowFix Plumbing',
    tradeCategory: 'Plumbing',
    subSkills: ['Emergency callout', 'Leaks', 'Bathrooms'],
    bio: 'Fast plumbing repairs, leak tracing and replacement taps, wastes and toilet parts for landlords and homeowners.',
    radiusMiles: 18,
    locationLabel: 'Kingston',
    externalLinks: {},
    photos: [],
    subscriptionTier: 'basic',
    isSubscriptionActive: true,
    trialEndsAt: '2026-09-18T12:00:00.000Z',
    averageRating: 4.7,
    reviewCount: 21,
  },
  {
    id: 'demo-finish-first-plastering',
    userId: 'demo-user-finish-first',
    businessName: 'Finish First Plastering',
    tradeCategory: 'Plastering',
    subSkills: ['Skimming', 'Dry lining', 'Ceilings'],
    bio: 'Room skims, damaged wall repairs and ceiling reboarding with dust control and realistic lead times.',
    radiusMiles: 22,
    locationLabel: 'Basingstoke',
    externalLinks: {},
    photos: [],
    subscriptionTier: 'basic',
    isSubscriptionActive: true,
    trialEndsAt: '2026-09-18T12:00:00.000Z',
    averageRating: 4.5,
    reviewCount: 13,
  },
  {
    id: 'demo-southside-renovations',
    userId: 'demo-user-southside-reno',
    businessName: 'Southside Renovations',
    tradeCategory: 'General Building',
    subSkills: ['Renovations', 'Groundworks', 'Brickwork'],
    bio: 'General building and renovation support for kitchens, bathrooms, garden rooms and small structural alterations.',
    radiusMiles: 40,
    locationLabel: 'Croydon',
    externalLinks: {},
    photos: [],
    subscriptionTier: 'featured',
    isSubscriptionActive: true,
    trialEndsAt: '2026-09-18T12:00:00.000Z',
    averageRating: 4.8,
    reviewCount: 24,
  },
];

export const demoJobs: Job[] = [
  { id: 'demo-job-hannah-bathroom', customerId: 'demo-customer-hannah-francis', targetTraderId: null, title: 'Hannah Francis needs a bathroom retiled', category: 'Tiling', propertyType: 'House', postcode: 'TW18', locationLabel: 'Staines-upon-Thames', urgency: 'Within 2 weeks', description: 'remove old bathroom tiles, prepare walls, waterproof shower area and fit new porcelain tiles around bath and basin.', aiGeneratedSpec: null, budgetRange: '£1,500–£5,000', photos: [], status: 'open', createdAt: now },
  { id: 'demo-job-kitchen-splashback', customerId: 'demo-customer-02', targetTraderId: null, title: 'Kitchen splashback tiling', category: 'Tiling', propertyType: 'Flat', postcode: 'KT1', locationLabel: 'Kingston', urgency: 'Flexible', description: 'fit metro tiles above worktops, include trims, grout and silicone finish around sockets and hob area.', aiGeneratedSpec: null, budgetRange: 'Under £500', photos: [], status: 'open', createdAt: now },
  { id: 'demo-job-ceiling-skim', customerId: 'demo-customer-03', targetTraderId: null, title: 'Living room ceiling skim', category: 'Plastering', propertyType: 'House', postcode: 'GU1', locationLabel: 'Guildford', urgency: 'Within 1 month', description: 'skim artex-style ceiling flat, repair two cracks and leave ready for painting after drying.', aiGeneratedSpec: null, budgetRange: '£500–£1,500', photos: [], status: 'open', createdAt: now },
  { id: 'demo-job-consumer-unit', customerId: 'demo-customer-04', targetTraderId: null, title: 'Consumer unit upgrade', category: 'Electrical', propertyType: 'House', postcode: 'W5', locationLabel: 'Ealing', urgency: 'Within 1 month', description: 'replace old fuse board with modern consumer unit and provide testing paperwork on completion.', aiGeneratedSpec: null, budgetRange: '£500–£1,500', photos: [], status: 'open', createdAt: now },
  { id: 'demo-job-leaking-shower', customerId: 'demo-customer-05', targetTraderId: null, title: 'Leaking shower repair', category: 'Plumbing', propertyType: 'Flat', postcode: 'SW18', locationLabel: 'Wandsworth', urgency: 'Urgent', description: 'shower leak coming through ceiling below, needs investigation, repair and clear written quote for making good.', aiGeneratedSpec: null, budgetRange: '£500–£1,500', photos: [], status: 'open', createdAt: now },
  { id: 'demo-job-internal-doors', customerId: 'demo-customer-06', targetTraderId: null, title: 'Hang six internal doors', category: 'Joinery', propertyType: 'House', postcode: 'TW9', locationLabel: 'Richmond', urgency: 'Flexible', description: 'hang six supplied internal doors, fit handles and adjust frames where needed.', aiGeneratedSpec: null, budgetRange: '£500–£1,500', photos: [], status: 'open', createdAt: now },
  { id: 'demo-job-flat-roof', customerId: 'demo-customer-07', targetTraderId: null, title: 'Flat roof repair over extension', category: 'Roofing', propertyType: 'House', postcode: 'SM2', locationLabel: 'Sutton', urgency: 'Within 2 weeks', description: 'water pooling on flat roof, suspected split felt near outlet. Needs inspection and repair quote.', aiGeneratedSpec: null, budgetRange: '£1,500–£5,000', photos: [], status: 'open', createdAt: now },
  { id: 'demo-job-garden-wall', customerId: 'demo-customer-08', targetTraderId: null, title: 'Rebuild small garden wall', category: 'General Building', propertyType: 'House', postcode: 'SL1', locationLabel: 'Slough', urgency: 'Within 1 month', description: 'remove loose brickwork and rebuild a low front garden wall, matching existing bricks where possible.', aiGeneratedSpec: null, budgetRange: '£500–£1,500', photos: [], status: 'open', createdAt: now },
  { id: 'demo-job-wet-room', customerId: 'demo-customer-09', targetTraderId: null, title: 'Wet room floor and tanking', category: 'Tiling', propertyType: 'Bungalow', postcode: 'GU21', locationLabel: 'Woking', urgency: 'Within 1 month', description: 'prepare wet room floor, install tanking system and tile floor with falls to drain.', aiGeneratedSpec: null, budgetRange: '£1,500–£5,000', photos: [], status: 'open', createdAt: now },
  { id: 'demo-job-shop-lighting', customerId: 'demo-customer-10', targetTraderId: null, title: 'Shop lighting upgrade', category: 'Electrical', propertyType: 'Commercial', postcode: 'UB8', locationLabel: 'Uxbridge', urgency: 'Flexible', description: 'replace old fluorescent lighting with LED panels in a small retail unit.', aiGeneratedSpec: null, budgetRange: '£1,500–£5,000', photos: [], status: 'open', createdAt: now },
  { id: 'demo-job-bathroom-suite', customerId: 'demo-customer-11', targetTraderId: null, title: 'Bathroom suite replacement', category: 'Plumbing', propertyType: 'House', postcode: 'RG1', locationLabel: 'Reading', urgency: 'Within 2 weeks', description: 'remove old bathroom suite, fit supplied bath, basin, toilet and new taps.', aiGeneratedSpec: null, budgetRange: '£1,500–£5,000', photos: [], status: 'open', createdAt: now },
  { id: 'demo-job-bedroom-skim', customerId: 'demo-customer-12', targetTraderId: null, title: 'Bedroom walls skimmed', category: 'Plastering', propertyType: 'Flat', postcode: 'BN17', locationLabel: 'Littlehampton', urgency: 'Flexible', description: 'skim four bedroom walls after wallpaper removal, fill chases and leave ready for mist coat.', aiGeneratedSpec: null, budgetRange: '£500–£1,500', photos: [], status: 'open', createdAt: now },
];
